// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const LocalEngine: typeof import('/workspace/projects/apps/web/src/utils/index').LocalEngine
  const LocalStorageEngine: typeof import('/workspace/projects/apps/web/src/utils/storage').LocalStorageEngine
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const RestfulEngine: typeof import('/workspace/projects/apps/web/src/utils/index').RestfulEngine
  const RestfulStorageEngine: typeof import('/workspace/projects/apps/web/src/utils/storage').RestfulStorageEngine
  const addPrefix: typeof import('/workspace/projects/apps/web/src/utils/index').addPrefix
  const browser: typeof import('wxt/browser').browser
  const checkImage: typeof import('/workspace/projects/apps/web/src/utils/index').checkImage
  const copyHtml: typeof import('/workspace/projects/apps/web/src/utils/clipboard').copyHtml
  const copyPlain: typeof import('/workspace/projects/apps/web/src/utils/clipboard').copyPlain
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const createTable: typeof import('/workspace/projects/apps/web/src/utils/index').createTable
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const downloadFile: typeof import('/workspace/projects/apps/web/src/utils/index').downloadFile
  const downloadMD: typeof import('/workspace/projects/apps/web/src/utils/index').downloadMD
  const exportHTML: typeof import('/workspace/projects/apps/web/src/utils/index').exportHTML
  const exportPDF: typeof import('/workspace/projects/apps/web/src/utils/index').exportPDF
  const exportPureHTML: typeof import('/workspace/projects/apps/web/src/utils/index').exportPureHTML
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const fileUpload: typeof import('/workspace/projects/apps/web/src/utils/file').fileUpload
  const formatDoc: typeof import('/workspace/projects/apps/web/src/utils/index').formatDoc
  const generatePureHTML: typeof import('/workspace/projects/apps/web/src/utils/index').generatePureHTML
  const getHtmlContent: typeof import('/workspace/projects/apps/web/src/utils/index').getHtmlContent
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const modifyHtmlContent: typeof import('/workspace/projects/apps/web/src/utils/index').modifyHtmlContent
  const postProcessHtml: typeof import('/workspace/projects/apps/web/src/utils/index').postProcessHtml
  const processClipboardContent: typeof import('/workspace/projects/apps/web/src/utils/index').processClipboardContent
  const removeLeft: typeof import('/workspace/projects/apps/web/src/utils/index').removeLeft
  const renderMarkdown: typeof import('/workspace/projects/apps/web/src/utils/index').renderMarkdown
  const sanitizeTitle: typeof import('/workspace/projects/apps/web/src/utils/index').sanitizeTitle
  const setupComponents: typeof import('/workspace/projects/apps/web/src/utils/setup-components').setupComponents
  const solveWeChatImage: typeof import('/workspace/projects/apps/web/src/utils/index').solveWeChatImage
  const storage: typeof import('wxt/utils/storage').storage
  const store: typeof import('/workspace/projects/apps/web/src/utils/storage').store
  const toBase64: typeof import('/workspace/projects/apps/web/src/utils/index').toBase64
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const useFolderFileSync: typeof import('/workspace/projects/apps/web/src/composables/useFolderFileSync').useFolderFileSync
  const useImportMarkdownContent: typeof import('/workspace/projects/apps/web/src/composables/index').useImportMarkdownContent
}
// for type re-export
declare global {
  // @ts-ignore
  export type { LocalStorageEngine, RestfulStorageEngine, StorageEngine } from '/workspace/projects/apps/web/src/utils/storage'
  import ('wxt/browser')
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import ('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import ('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import ('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import ('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import ('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { AutoMount, AutoMountOptions, ContentScriptAnchoredOptions, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptModalPositioningOptions, ContentScriptOverlayAlignment, ContentScriptOverlayPositioningOptions, ContentScriptPositioningOptions, ContentScriptUi, ContentScriptUiOptions, StopAutoMount } from 'wxt/utils/content-script-ui/types'
  import ('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import ('wxt/utils/define-app-config')
  // @ts-ignore
  export type { InjectScriptOptions, ScriptPublicPath } from 'wxt/utils/inject-script'
  import ('wxt/utils/inject-script')
  // @ts-ignore
  export type { MigrationError, StorageArea, StorageAreaChanges, StorageItemKey, WxtStorage, WxtStorageItem } from 'wxt/utils/storage'
  import ('/workspace/projects/apps/web/src/utils/storage')
}
